#!/usr/bin/perl
# Ejemplo 9: Sintaxis de while en perl
#					while ( [condición] ) {
#						[sentencias]
#					}

print " \n Ingrese un número entre 0 y 100: ";
chop ( $numero = <STDIN> );
while ( $numero < 100 ) {
	print "\n";
	print "		El número es: $numero \n ";
	$numero = $numero + 1 ;
}
